version: "2"
services:
  data_server:
    container_name: data_server
    restart: always
    build: 
      context: .
      dockerfile: Server.Dockerfile
    ports:
      - "1337:1337"
  data_presenter_1:
    container_name: data_presenter_1
    restart: always
    build:
      context: .
      dockerfile: Provider.Dockerfile
    command: 
      node ./dataPresenter/scripts/dataProvider.js SampleSignal1 RandomSignal1
  
  data_presenter_2:
    container_name: data_presenter_2
    restart: always
    build:
      context: .
      dockerfile: Provider.Dockerfile
    command: 
      node ./dataPresenter/scripts/dataProvider.js SampleSignal2 RandomSignal2
      
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"